server:
  port: 10100

spring:
  application:
    name: higo-ws-holder-service
  profiles:
    active: @profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "shutdown"